# Form implementation generated from reading ui file 'takeFiles.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFileDialog


class Ui_takeFiles(object):
    def setupUi(self, takeFiles):
        takeFiles.setObjectName("takeFiles")
        takeFiles.resize(745, 163)
        takeFiles.setStyleSheet("background-color: rgb(51, 252, 255);")
        self.label = QtWidgets.QLabel(takeFiles)
        self.label.setGeometry(QtCore.QRect(10, 40, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(takeFiles)
        self.lineEdit.setGeometry(QtCore.QRect(180, 30, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "color: rgb(0, 0, 0);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(takeFiles)
        self.pushButton.setGeometry(QtCore.QRect(630, 35, 93, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(takeFiles)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(takeFiles)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 100, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "color: rgb(0, 0, 0);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(takeFiles)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 105, 93, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(takeFiles)
        QtCore.QMetaObject.connectSlotsByName(takeFiles)

    def retranslateUi(self, takeFiles):
        _translate = QtCore.QCoreApplication.translate
        takeFiles.setWindowTitle(_translate("takeFiles", "Выберите папку с файлами Нейтрон"))
        self.label.setText(_translate("takeFiles", "Нейтрон"))
        self.lineEdit.setPlaceholderText(_translate("takeFiles", "Введите папку c нужными файлами"))
        self.pushButton.setText(_translate("takeFiles", "Обзор"))
        self.label_2.setText(_translate("takeFiles", "Давление - Ураган"))
        self.lineEdit_2.setPlaceholderText(_translate("takeFiles", "Введите папку c нужными файлами"))
        self.pushButton_2.setText(_translate("takeFiles", "Обзор"))

    def getFileDirectory(self, filename):
        dirlist = QFileDialog.getExistingDirectory()
        if filename == 'path1files':
            self.lineEdit.setText(dirlist)
        else:
            self.lineEdit_2.setText(dirlist)
        with open(filename + '.ini', 'w') as f:
            f.write(dirlist)
        print(dirlist)
